/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["service_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /history - List transcription history. */
        get: operations["list_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /history/:id - Get a single transcription. */
        get: operations["get_history_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keybind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /keybind - Uninstall the keybinding. */
        delete: operations["uninstall_keybind"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keybind/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /keybind/install - Install a keybinding. */
        post: operations["install_keybind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keybind/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /keybind/status - Get keybinding status. */
        get: operations["get_keybind_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /logs - Get application and transcription logs. */
        get: operations["get_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_meetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["meeting_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stop_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggle_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_meeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /meetings/:id/retry — re-run transcription on the durable mp3 from a
         *     previously failed meeting. Useful when the backend was the cause (e.g. the
         *     5-min Bun-fetch idle bug in InferenceServerManager) and the audio is fine.
         * @description Validates: meeting exists, is in `error` state, and its mp3 is still on
         *     disk. Spawns the retry in a tokio task and returns 202 immediately so the
         *     renderer can begin polling `/meetings/:id` for the status flip.
         */
        post: operations["retry_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /provider - Get provider configuration. */
        get: operations["get_provider_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /provider/status - Get provider status and health. */
        get: operations["get_provider_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets the current recording status.
         * @description Pass `?style=waybar` for a Waybar-formatted `{text, class, tooltip}` payload.
         */
        get: operations["recording_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/deps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /system/deps - report availability of required external tools. */
        get: operations["get_system_deps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/install-ffmpeg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /system/install-ffmpeg - kick off an app-local FFmpeg install.
         * @description Idempotent w.r.t. already-installed: if ffmpeg already resolves (either as
         *     the sidecar binary or on PATH), the response is 200 with phase=`done` and
         *     no work happens.
         *
         *     Returns 202 + current state when an install is started (or kicked off
         *     after a previous error). Returns 409 + current state when an install is
         *     already in flight.
         */
        post: operations["install_ffmpeg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/install-ffmpeg/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /system/install-ffmpeg/status - poll the current install state. */
        get: operations["get_install_ffmpeg_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggles recording on or off with optional per-job options. */
        post: operations["toggle_recording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** PUT /update/auto - Enable or disable auto-update. */
        put: operations["set_auto_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /update/check - Check for available updates. */
        get: operations["check_update"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /update/install - Install an update. */
        post: operations["install_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["service_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for auto-update toggle. */
        AutoUpdateRequest: {
            /** @description Enable or disable auto-update */
            enabled: boolean;
        };
        /** @description Response body for the auto-update toggle endpoint. */
        AutoUpdateResponse: {
            auto_update: boolean;
            message: string;
            success: boolean;
        };
        /** @description The `last_completed_job` nested block inside `RecordingStatusResponse`. */
        CompletedJobSummary: {
            created_at: string;
            /** Format: int64 */
            history_id?: number | null;
            job_id: string;
            text: string;
        };
        /** @description A single history entry with formatted display data. */
        HistoryEntry: {
            audio_path: string;
            created_at: string;
            /** Format: int64 */
            id: number;
            text: string;
        };
        /**
         * @description Phase string for the install status endpoint. Renderer uses this to drive
         *     progress UI and decide when to stop polling.
         * @enum {string}
         */
        InstallPhase: "idle" | "starting" | "downloading" | "extracting" | "done" | "error";
        /** @description Request body for keybind install. */
        InstallRequest: {
            /** @description Custom key string (e.g., "SUPER+R" or "SUPER SHIFT, T") */
            key?: string | null;
        };
        /** @description Response body for POST /keybind/install. */
        InstallResponse: {
            backup_path?: string | null;
            config_path?: string | null;
            display_key?: string | null;
            message: string;
            success: boolean;
        };
        /**
         * @description Flattened install state — easier to consume from TypeScript than a tagged
         *     union. Fields not relevant to the current phase are `None`.
         */
        InstallStatusResponse: {
            /** @description Set on `Done`. */
            binaryPath?: string | null;
            /**
             * Format: int64
             * @description Set during `Downloading`.
             */
            downloadedBytes?: number | null;
            /** @description Set on `Error`. */
            message?: string | null;
            /**
             * Format: int32
             * @description Convenience field; `0..=100` during download, `None` otherwise.
             */
            percent?: number | null;
            phase: components["schemas"]["InstallPhase"];
            /**
             * Format: int64
             * @description Set during `Downloading`. May be 0 before headers arrive.
             */
            totalBytes?: number | null;
        };
        /** @description Status of Audetic keybinding installation */
        KeybindStatus: {
            /** @description The command bound to the key */
            command: string;
            config_path: string;
            /** @description Display string for the keybinding (e.g., "SUPER + R") */
            display_key: string;
            /** @enum {string} */
            status: "installed";
        } | {
            config_path?: string | null;
            /** @enum {string} */
            status: "not_installed";
        } | {
            /** @enum {string} */
            status: "no_config";
        };
        /** @description Combined logs result containing both app logs and transcription history. */
        LogsResult: {
            /** @description Application logs from systemd journal */
            app_logs: string[];
            /** @description Recent transcription entries */
            transcriptions: components["schemas"]["HistoryEntry"][];
        };
        /** @description Response for GET /meetings/:id. */
        MeetingDetailResponse: {
            audio_path: string;
            completed_at?: string | null;
            created_at: string;
            /** Format: int64 */
            duration_seconds?: number | null;
            error?: string | null;
            /** Format: int64 */
            id: number;
            started_at: string;
            status: string;
            title?: string | null;
            transcript_path?: string | null;
            transcript_text?: string | null;
        };
        /** @description Response for POST /meetings/:id/retry. */
        MeetingRetryResponse: {
            /** Format: int64 */
            meeting_id: number;
            message: string;
            success: boolean;
        };
        /** @description Request body for start/toggle endpoints. */
        MeetingStartRequest: {
            title?: string | null;
        };
        /** @description Response for POST /meetings/start. */
        MeetingStartResponse: {
            audio_path: string;
            capture_state: string;
            /** Format: int64 */
            meeting_id: number;
            message: string;
            success: boolean;
        };
        /** @description Default (non-waybar) response for GET /meetings/status. */
        MeetingStatusResponse: {
            active: boolean;
            audio_path?: string | null;
            /** Format: int64 */
            duration_seconds?: number | null;
            last_error?: string | null;
            /** Format: int64 */
            meeting_id?: number | null;
            phase: string;
            title?: string | null;
        };
        /** @description Response for POST /meetings/stop and POST /meetings/cancel. */
        MeetingStopResponse: {
            /** Format: int64 */
            duration_seconds: number;
            /** Format: int64 */
            meeting_id: number;
            message: string;
            success: boolean;
        };
        /** @description Summary of one meeting as returned in GET /meetings. */
        MeetingSummary: {
            audio_path: string;
            /** Format: int64 */
            duration_seconds?: number | null;
            /** Format: int64 */
            id: number;
            started_at: string;
            status: string;
            title?: string | null;
            transcript_path?: string | null;
        };
        /**
         * @description Response for POST /meetings/toggle — shape varies by whether a
         *     meeting was started or stopped. Extra fields are only present
         *     when relevant; both `duration_seconds` and `audio_path` may be null.
         */
        MeetingToggleResponse: {
            audio_path?: string | null;
            capture_state?: string | null;
            /** Format: int64 */
            duration_seconds?: number | null;
            /** Format: int64 */
            meeting_id: number;
            message: string;
            phase: string;
            success: boolean;
        };
        /** @description Response for GET /meetings. */
        MeetingsListResponse: {
            meetings: components["schemas"]["MeetingSummary"][];
        };
        /** @description Get a summary of the current provider configuration. */
        ProviderInfo: {
            api_endpoint?: string | null;
            command_path?: string | null;
            has_api_key: boolean;
            language?: string | null;
            model?: string | null;
            model_path?: string | null;
            provider?: string | null;
        };
        /** @description Status of the transcription provider */
        ProviderStatus: {
            language?: string | null;
            model?: string | null;
            provider: string;
            /** @enum {string} */
            status: "ready";
        } | {
            error: string;
            provider: string;
            /** @enum {string} */
            status: "config_error";
        } | {
            /** @enum {string} */
            status: "not_configured";
        };
        /** @description Default (non-waybar) response for GET /status. */
        RecordingStatusResponse: {
            job_id?: string | null;
            last_completed_job?: null | components["schemas"]["CompletedJobSummary"];
            last_error?: string | null;
            phase: string;
            recording: boolean;
        };
        /** @description Response for GET / — service identity and basic status. */
        ServiceInfo: {
            service: string;
            status: string;
            version: string;
        };
        /** @description Availability of external tools the daemon depends on. */
        SystemDeps: {
            /**
             * @description Whether `ffmpeg` resolves — either app-local sidecar or on PATH.
             *     Required for meeting audio compression before upload.
             */
            ffmpeg: boolean;
        };
        /**
         * @description Request body for the toggle recording endpoint.
         *     All fields are optional - if not provided, defaults are used from config.
         */
        ToggleRequest: {
            /** @description Whether to auto-paste/inject text into the focused app (default: from config) */
            auto_paste?: boolean | null;
            /** @description Whether to copy the transcription to clipboard (default: true) */
            copy_to_clipboard?: boolean | null;
        };
        /** @description Response body for POST /toggle. */
        ToggleResponse: {
            job_id?: string | null;
            message: string;
            phase: string;
            success: boolean;
        };
        /** @description Response body for DELETE /keybind. */
        UninstallResponse: {
            backup_path?: string | null;
            config_path?: string | null;
            message: string;
            removed?: boolean | null;
            success: boolean;
        };
        /** @description Request body for update install. */
        UpdateInstallRequest: {
            /** @description Channel override (e.g., "stable", "beta") */
            channel?: string | null;
            /** @description Force update even if versions match */
            force?: boolean | null;
        };
        UpdateReport: {
            current_version: string;
            installed: boolean;
            message: string;
            remote_version?: string | null;
            restart_required: boolean;
        };
        /** @description Response for GET /version. */
        VersionInfo: {
            name: string;
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    service_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service identity and liveness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
        };
    };
    list_history: {
        parameters: {
            query?: {
                /** @description Search query */
                q?: string | null;
                /** @description Start date (YYYY-MM-DD) */
                from?: string | null;
                /** @description End date (YYYY-MM-DD) */
                to?: string | null;
                /** @description Maximum results (default 20) */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcription entries matching the query */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
        };
    };
    get_history_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transcription history id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcription entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uninstall_keybind: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uninstall result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UninstallResponse"];
                };
            };
        };
    };
    install_keybind: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallRequest"];
            };
        };
        responses: {
            /** @description Install result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallResponse"];
                };
            };
        };
    };
    get_keybind_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current keybind installation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeybindStatus"];
                };
            };
        };
    };
    get_logs: {
        parameters: {
            query?: {
                /** @description Number of log entries (default 30) */
                lines?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined app + transcription logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResult"];
                };
            };
        };
    };
    list_meetings: {
        parameters: {
            query?: {
                /** @description Maximum meetings to return (default 20) */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent meetings, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingsListResponse"];
                };
            };
        };
    };
    cancel_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting cancelled without transcribing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStopResponse"];
                };
            };
            /** @description No meeting recording in progress to cancel */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingStartRequest"];
            };
        };
        responses: {
            /** @description Meeting started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStartResponse"];
                };
            };
            /** @description A meeting is already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meeting_status: {
        parameters: {
            query?: {
                /** @description Set to `waybar` for Waybar-formatted response */
                style?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting status (default JSON shape) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStatusResponse"];
                };
            };
        };
    };
    stop_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting stopped and transcription queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStopResponse"];
                };
            };
            /** @description No meeting recording in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggle_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingStartRequest"];
            };
        };
        responses: {
            /** @description Meeting started or stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingToggleResponse"];
                };
            };
        };
    };
    get_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetailResponse"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retry kicked off; poll /meetings/:id */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRetryResponse"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Meeting is not in a retry-eligible state, or audio file missing */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_provider_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current provider configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfo"];
                };
            };
        };
    };
    get_provider_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"];
                };
            };
        };
    };
    recording_status: {
        parameters: {
            query?: {
                /** @description Set to `waybar` for Waybar-formatted response */
                style?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recording status (default JSON shape) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingStatusResponse"];
                };
            };
        };
    };
    get_system_deps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description External tool availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDeps"];
                };
            };
        };
    };
    install_ffmpeg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FFmpeg already installed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
            /** @description Install kicked off */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
            /** @description Install already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
        };
    };
    get_install_ffmpeg_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current install state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
        };
    };
    toggle_recording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Optional per-job overrides */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleRequest"];
            };
        };
        responses: {
            /** @description Toggle dispatched; reflects immediate phase */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleResponse"];
                };
            };
        };
    };
    set_auto_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoUpdateRequest"];
            };
        };
        responses: {
            /** @description Auto-update flag after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoUpdateResponse"];
                };
            };
        };
    };
    check_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current vs available version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateReport"];
                };
            };
        };
    };
    install_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInstallRequest"];
            };
        };
        responses: {
            /** @description Result of the install attempt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateReport"];
                };
            };
        };
    };
    service_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daemon name and version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
}
