/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["service_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transcription history. */
        get: operations["list_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single transcription. */
        get: operations["get_history_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keybind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Uninstall the keybinding. */
        delete: operations["uninstall_keybind"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keybind/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install a keybinding. */
        post: operations["install_keybind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keybind/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get keybinding status. */
        get: operations["get_keybind_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get application and transcription logs. */
        get: operations["get_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_meetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a media file as a new meeting.
         * @description Accepts a `multipart/form-data` body with:
         *     - `file`: the audio or video bytes (required)
         *     - `title`: optional human-readable title; defaults to the filename
         *       stem if absent
         *
         *     The file is streamed chunk-by-chunk into a temp file under the meetings
         *     directory, then handed to `meeting::import_meeting_file`, which moves
         *     it into place, inserts the DB row, and spawns the processing pipeline.
         *     Returns 202 with the new meeting id; clients poll `GET /meetings/{id}`
         *     for status. The response intentionally omits the storage path —
         *     callers shouldn't depend on the filesystem layout.
         */
        post: operations["import_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["meeting_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stop_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggle_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_meeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a meeting's audio file for in-browser playback. Used by the review
         *     UI so the user can listen back before choosing trim points. Resolves the
         *     file actually on disk — the row points at the `.wav` while review is
         *     pending and the `.mp3` after processing. Served via `ServeFile`, which
         *     honours HTTP Range requests so the `<audio>` element can seek.
         */
        get: operations["meeting_audio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run transcription on the durable mp3 from a previously failed
         *     meeting. Useful when the backend was the cause (e.g. the 5-min
         *     Bun-fetch idle bug in InferenceServerManager) and the audio is fine.
         * @description Validates: meeting exists, is in `error` state, and its mp3 is still
         *     on disk. Spawns the retry in a tokio task and returns 202
         *     immediately so the renderer can begin polling for the status flip.
         */
        post: operations["retry_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post-processing/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every event kind the daemon can fire. */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post-processing/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all jobs (optionally filtered by event kind). */
        get: operations["list_jobs"];
        put?: never;
        /** Create a new job. */
        post: operations["create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post-processing/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete: operations["delete_job"];
        options?: never;
        head?: never;
        patch: operations["update_job"];
        trace?: never;
    };
    "/post-processing/jobs/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a job once with a synthetic payload. Useful for "did I write the
         *     command right?" before waiting for a real event.
         */
        post: operations["test_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get provider configuration. */
        get: operations["get_provider_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the raw `WhisperConfig` (including any API key) so the CLI wizard can
         *     pre-fill existing values. Loopback-only, same trust boundary as reading
         *     `~/.config/audetic/config.toml` directly.
         */
        get: operations["get_provider_raw_config"];
        /**
         * Replace the provider configuration. Backs up the existing `config.toml`
         *     before writing.
         */
        put: operations["set_raw_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset the provider configuration to defaults. Backs up first. */
        post: operations["reset_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get provider status and health. */
        get: operations["get_provider_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test the currently-configured provider, optionally against an audio file. */
        post: operations["run_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets the current recording status.
         * @description Pass `?style=waybar` for a Waybar-formatted `{text, class, tooltip}` payload.
         */
        get: operations["recording_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/deps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report availability of required external tools. */
        get: operations["get_system_deps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/install-ffmpeg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kick off an app-local FFmpeg install.
         * @description Idempotent w.r.t. already-installed: if ffmpeg already resolves (either as
         *     the sidecar binary or on PATH), the response is 200 with phase=`done` and
         *     no work happens.
         *
         *     Returns 202 + current state when an install is started (or kicked off
         *     after a previous error). Returns 409 + current state when an install is
         *     already in flight.
         */
        post: operations["install_ffmpeg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/install-ffmpeg/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll the current install state. */
        get: operations["get_install_ffmpeg_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggles recording on or off with optional per-job options. */
        post: operations["toggle_recording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current auto-update flag. */
        get: operations["get_auto_update"];
        /** Enable or disable auto-update. */
        put: operations["set_auto_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check for available updates. */
        get: operations["check_update"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install an update. */
        post: operations["install_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["service_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description What a job does when matched.
         *
         *     Stored on disk as two columns: `action_type` (the tag) and
         *     `action_config` (a JSON blob holding the variant fields). The
         *     [`Action`] serde shape mirrors this so we can round-trip via
         *     `serde_json` when materializing the row.
         */
        Action: {
            command: string;
            /** Format: int64 */
            timeout_seconds?: number;
            /** @enum {string} */
            type: "command";
        };
        /** @description Request body for auto-update toggle. */
        AutoUpdateRequest: {
            /** @description Enable or disable auto-update */
            enabled: boolean;
        };
        /** @description Response body for the auto-update toggle endpoint. */
        AutoUpdateResponse: {
            auto_update: boolean;
            message: string;
            success: boolean;
        };
        /** @description Response body for the auto-update getter. */
        AutoUpdateState: {
            enabled: boolean;
        };
        /** @description The `last_completed_job` nested block inside `RecordingStatusResponse`. */
        CompletedJobSummary: {
            created_at: string;
            /** Format: int64 */
            history_id?: number | null;
            job_id: string;
            text: string;
        };
        DeleteResponse: {
            /** Format: int64 */
            id: number;
            success: boolean;
        };
        /** @description One supported event in the `events` listing. */
        EventDescriptor: {
            /** @description What the JSON `data` shape contains when this event fires. */
            description: string;
            /** @description Human-readable label for UI dropdowns. */
            label: string;
            /**
             * @description Wire identifier persisted in `post_processing_jobs.event` and
             *     accepted in the `event` field of new/updated jobs.
             */
            name: string;
        };
        /**
         * @description Stable identifier for an event type, as stored in the
         *     `post_processing_jobs.event` column and exposed over the API.
         * @enum {string}
         */
        EventKind: "dictation.completed" | "meeting.completed";
        EventsListResponse: {
            events: components["schemas"]["EventDescriptor"][];
        };
        /** @description A single history entry with formatted display data. */
        HistoryEntry: {
            audio_path: string;
            created_at: string;
            /** Format: int64 */
            id: number;
            text: string;
        };
        /**
         * @description Phase string for the install status endpoint. Renderer uses this to drive
         *     progress UI and decide when to stop polling.
         * @enum {string}
         */
        InstallPhase: "idle" | "starting" | "downloading" | "extracting" | "done" | "error";
        /** @description Request body for keybind install. */
        InstallRequest: {
            /** @description Custom key string (e.g., "SUPER+R" or "SUPER SHIFT, T") */
            key?: string | null;
        };
        /**
         * @description Result of installing a hyprland binding: the resulting key
         *     combination, where the config was edited, and the backup path.
         */
        InstallResponse: {
            backup_path?: string | null;
            config_path?: string | null;
            display_key?: string | null;
            message: string;
            success: boolean;
        };
        /**
         * @description Flattened install state — easier to consume from TypeScript than a tagged
         *     union. Fields not relevant to the current phase are `None`.
         */
        InstallStatusResponse: {
            /** @description Set on `Done`. */
            binaryPath?: string | null;
            /**
             * Format: int64
             * @description Set during `Downloading`.
             */
            downloadedBytes?: number | null;
            /** @description Set on `Error`. */
            message?: string | null;
            /**
             * Format: int32
             * @description Convenience field; `0..=100` during download, `None` otherwise.
             */
            percent?: number | null;
            phase: components["schemas"]["InstallPhase"];
            /**
             * Format: int64
             * @description Set during `Downloading`. May be 0 before headers arrive.
             */
            totalBytes?: number | null;
        };
        /** @description A row from `post_processing_jobs`, materialized into a strong type. */
        Job: {
            action: components["schemas"]["Action"];
            created_at: string;
            enabled: boolean;
            event: components["schemas"]["EventKind"];
            /** Format: int64 */
            id: number;
            name: string;
            updated_at: string;
        };
        JobsListResponse: {
            jobs: components["schemas"]["Job"][];
        };
        /**
         * @description Status of the Audetic toggle keybinding.
         *
         *     `command`/`config_path` are populated on Linux (the Hyprland binding and the
         *     file it lives in) and `None` on macOS, where the daemon owns the binding
         *     directly. `Disabled` is macOS-only; `NotInstalled`/`NoConfig` are Linux-only.
         */
        KeybindStatus: {
            command?: string | null;
            config_path?: string | null;
            display_key: string;
            /** @enum {string} */
            status: "installed";
        } | {
            config_path?: string | null;
            /** @enum {string} */
            status: "not_installed";
        } | {
            /** @enum {string} */
            status: "no_config";
        } | {
            /** @enum {string} */
            status: "disabled";
        } | {
            display_key: string;
            error: string;
            /** @enum {string} */
            status: "failed";
        };
        /**
         * @description [`KeybindStatus`] plus the platform it came from. Flattened on the wire, so
         *     the JSON stays `{ "platform": …, "status": …, … }` — the top-level `status`
         *     string the CLI reads is preserved.
         */
        KeybindStatusResponse: components["schemas"]["KeybindStatus"] & {
            platform: components["schemas"]["Platform"];
        };
        /** @description Combined logs result containing both app logs and transcription history. */
        LogsResult: {
            /** @description Application logs from systemd journal */
            app_logs: string[];
            /** @description Recent transcription entries */
            transcriptions: components["schemas"]["HistoryEntry"][];
        };
        /**
         * @description Request body for the confirm endpoint. Both bounds are optional; omitting
         *     one keeps that edge of the recording. Both omitted sends it untouched.
         */
        MeetingConfirmRequest: {
            /**
             * Format: double
             * @description New end of the recording, in seconds (clamped to the recording).
             */
            end_seconds?: number | null;
            /**
             * Format: double
             * @description New start of the recording, in seconds (clamped to the recording).
             */
            start_seconds?: number | null;
        };
        /** @description Full meeting record including transcript text when available. */
        MeetingDetailResponse: {
            audio_path: string;
            completed_at?: string | null;
            created_at: string;
            /** Format: int64 */
            duration_seconds?: number | null;
            error?: string | null;
            /** Format: int64 */
            id: number;
            started_at: string;
            status: string;
            title?: string | null;
            transcript_path?: string | null;
            transcript_text?: string | null;
        };
        /**
         * @description Confirmation that an imported media file has been accepted as a new
         *     meeting. The processing pipeline runs in the background; clients poll
         *     `GET /meetings/{id}` for phase progression and the final transcript.
         */
        MeetingImportResponse: {
            /** Format: int64 */
            meeting_id: number;
            message: string;
            success: boolean;
        };
        /**
         * @description Confirmation that a failed meeting's transcription has been
         *     re-queued; the actual work runs in the background.
         */
        MeetingRetryResponse: {
            /** Format: int64 */
            meeting_id: number;
            message: string;
            success: boolean;
        };
        /** @description Request body for start/toggle endpoints. */
        MeetingStartRequest: {
            title?: string | null;
        };
        /**
         * @description Confirmation that a meeting recording has begun: the assigned id,
         *     where audio is being written, and capture-source state.
         */
        MeetingStartResponse: {
            audio_path: string;
            capture_state: string;
            /** Format: int64 */
            meeting_id: number;
            message: string;
            success: boolean;
        };
        /**
         * @description Default (non-waybar) meeting status snapshot. The waybar variant
         *     has a different shape — see the union response on the handler.
         */
        MeetingStatusResponse: {
            active: boolean;
            audio_path?: string | null;
            /** Format: int64 */
            duration_seconds?: number | null;
            last_error?: string | null;
            /** Format: int64 */
            meeting_id?: number | null;
            phase: string;
            title?: string | null;
        };
        /**
         * @description Result of ending a meeting (stop or cancel): the meeting id and how
         *     long it ran.
         */
        MeetingStopResponse: {
            /** Format: int64 */
            duration_seconds: number;
            /** Format: int64 */
            meeting_id: number;
            message: string;
            success: boolean;
        };
        /**
         * @description Summary of one meeting in a list response — enough to render a row
         *     without loading the full transcript.
         */
        MeetingSummary: {
            audio_path: string;
            /** Format: int64 */
            duration_seconds?: number | null;
            /** Format: int64 */
            id: number;
            started_at: string;
            status: string;
            title?: string | null;
            transcript_path?: string | null;
        };
        /**
         * @description Result of a meeting toggle. Shape varies by whether a meeting was
         *     started or stopped: `audio_path`/`capture_state` appear on start,
         *     `duration_seconds` appears on stop, hence the optional fields.
         */
        MeetingToggleResponse: {
            audio_path?: string | null;
            capture_state?: string | null;
            /** Format: int64 */
            duration_seconds?: number | null;
            /** Format: int64 */
            meeting_id: number;
            message: string;
            phase: string;
            success: boolean;
        };
        /** @description Paginated list of meeting summaries. */
        MeetingsListResponse: {
            meetings: components["schemas"]["MeetingSummary"][];
        };
        /**
         * @description Request body for `POST /api/post-processing/jobs`. Same shape the
         *     CLI builds when piping args from `audetic post-processing add`.
         */
        NewJob: {
            action: components["schemas"]["Action"];
            enabled?: boolean;
            event: components["schemas"]["EventKind"];
            name: string;
        };
        /**
         * @description Which platform's keybind mechanism this daemon build uses. Lets the web UI
         *     render the right affordances (Hyprland config vs. native global hotkey).
         * @enum {string}
         */
        Platform: "macos" | "linux";
        /** @description Get a summary of the current provider configuration. */
        ProviderInfo: {
            api_endpoint?: string | null;
            command_path?: string | null;
            has_api_key: boolean;
            language?: string | null;
            model?: string | null;
            model_path?: string | null;
            provider?: string | null;
        };
        /** @description Status of the transcription provider */
        ProviderStatus: {
            language?: string | null;
            model?: string | null;
            provider: string;
            /** @enum {string} */
            status: "ready";
        } | {
            error: string;
            provider: string;
            /** @enum {string} */
            status: "config_error";
        } | {
            /** @enum {string} */
            status: "not_configured";
        };
        /** @description Request body for `POST /provider/test`. */
        ProviderTestRequest: {
            /**
             * @description Optional path to an audio file to transcribe. When omitted, the daemon
             *     only validates that the configured provider initializes.
             */
            file?: string | null;
        };
        /** @description Result of testing a provider */
        ProviderTestResult: {
            /**
             * Format: double
             * @description Time taken in seconds
             */
            duration_secs: number;
            /** @description Error message (if failed) */
            error?: string | null;
            /** @description Whether the test succeeded */
            success: boolean;
            /** @description Transcription result (if successful) */
            transcription?: string | null;
        };
        /**
         * @description Default (non-waybar) recording status snapshot. The waybar variant
         *     is a different shape — see the union response on the handler.
         */
        RecordingStatusResponse: {
            job_id?: string | null;
            last_completed_job?: null | components["schemas"]["CompletedJobSummary"];
            last_error?: string | null;
            phase: string;
            recording: boolean;
        };
        /** @description Response for GET / — service identity and basic status. */
        ServiceInfo: {
            service: string;
            status: string;
            version: string;
        };
        /** @description Availability of external tools the daemon depends on. */
        SystemDeps: {
            /**
             * @description Whether `ffmpeg` resolves — either app-local sidecar or on PATH.
             *     Required for meeting audio compression before upload.
             */
            ffmpeg: boolean;
        };
        /** @description Result body for `POST /jobs/:id/test`. */
        TestJobResponse: {
            /** Format: int32 */
            exit_code?: number | null;
            stderr: string;
            stdout: string;
            success: boolean;
            timed_out: boolean;
        };
        /**
         * @description Request body for the toggle recording endpoint.
         *     All fields are optional - if not provided, defaults are used from config.
         */
        ToggleRequest: {
            /** @description Whether to auto-paste/inject text into the focused app (default: from config) */
            auto_paste?: boolean | null;
            /** @description Whether to copy the transcription to clipboard (default: true) */
            copy_to_clipboard?: boolean | null;
        };
        /**
         * @description Result of toggling recording: lifecycle phase, the job id when one
         *     is being processed, and a human-readable status message.
         */
        ToggleResponse: {
            job_id?: string | null;
            message: string;
            phase: string;
            success: boolean;
        };
        /** @description Result of removing an Audetic-managed hyprland binding. */
        UninstallResponse: {
            backup_path?: string | null;
            config_path?: string | null;
            message: string;
            removed?: boolean | null;
            success: boolean;
        };
        /** @description Request body for update install. */
        UpdateInstallRequest: {
            /** @description Channel override (e.g., "stable", "beta") */
            channel?: string | null;
            /** @description Force update even if versions match */
            force?: boolean | null;
        };
        /**
         * @description Request body for `PATCH /api/post-processing/jobs/:id`. All fields
         *     optional — only what's supplied is updated.
         */
        UpdateJob: {
            action?: null | components["schemas"]["Action"];
            enabled?: boolean | null;
            event?: null | components["schemas"]["EventKind"];
            name?: string | null;
        };
        UpdateReport: {
            current_version: string;
            installed: boolean;
            message: string;
            remote_version?: string | null;
            restart_required: boolean;
        };
        /** @description Response for GET /version. */
        VersionInfo: {
            name: string;
            version: string;
        };
        WhisperConfig: {
            /** @default null */
            api_endpoint: string | null;
            /** @default null */
            api_key: string | null;
            /** @default null */
            command_path: string | null;
            /** @default en */
            language: string | null;
            /** @default base */
            model: string | null;
            /** @default null */
            model_path: string | null;
            /** @default audetic-api */
            provider: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    service_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service identity and liveness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
        };
    };
    list_history: {
        parameters: {
            query?: {
                /** @description Search query */
                q?: string | null;
                /** @description Start date (YYYY-MM-DD) */
                from?: string | null;
                /** @description End date (YYYY-MM-DD) */
                to?: string | null;
                /** @description Maximum results (default 20) */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcription entries matching the query */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
        };
    };
    get_history_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transcription history id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcription entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uninstall_keybind: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uninstall result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UninstallResponse"];
                };
            };
        };
    };
    install_keybind: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallRequest"];
            };
        };
        responses: {
            /** @description Install result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallResponse"];
                };
            };
        };
    };
    get_keybind_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current keybind installation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeybindStatusResponse"];
                };
            };
        };
    };
    get_logs: {
        parameters: {
            query?: {
                /** @description Number of log entries (default 30) */
                lines?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined app + transcription logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResult"];
                };
            };
        };
    };
    list_meetings: {
        parameters: {
            query?: {
                /** @description Maximum meetings to return (default 20) */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent meetings, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingsListResponse"];
                };
            };
        };
    };
    cancel_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting cancelled without transcribing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStopResponse"];
                };
            };
            /** @description No meeting recording in progress to cancel */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirm_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingConfirmRequest"];
            };
        };
        responses: {
            /** @description Meeting confirmed; transcription queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStopResponse"];
                };
            };
            /** @description Invalid trim range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No meeting awaiting review */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description File upload with optional title */
        requestBody?: {
            content: {
                "multipart/form-data": unknown;
            };
        };
        responses: {
            /** @description Import accepted; poll /meetings/:id */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingImportResponse"];
                };
            };
            /** @description Missing file part or unsupported extension */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to stage upload or insert meeting row */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingStartRequest"];
            };
        };
        responses: {
            /** @description Meeting started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStartResponse"];
                };
            };
            /** @description A meeting is already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meeting_status: {
        parameters: {
            query?: {
                /** @description Set to `waybar` for Waybar-formatted response */
                style?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting status (default JSON shape) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStatusResponse"];
                };
            };
        };
    };
    stop_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting stopped; awaiting review before transcription */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingStopResponse"];
                };
            };
            /** @description No meeting recording in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggle_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingStartRequest"];
            };
        };
        responses: {
            /** @description Meeting started or stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingToggleResponse"];
                };
            };
        };
    };
    get_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetailResponse"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meeting_audio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio bytes (supports Range) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Meeting or audio file not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retry kicked off; poll /meetings/:id */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRetryResponse"];
                };
            };
            /** @description Meeting not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Meeting is not in a retry-eligible state, or audio file missing */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported event kinds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsListResponse"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                /** @description Filter to a single event kind (e.g. `meeting.completed`). */
                event?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse"];
                };
            };
            /** @description Unknown event filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewJob"];
            };
        };
        responses: {
            /** @description Created job */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJob"];
            };
        };
        responses: {
            /** @description Updated job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    test_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestJobResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_provider_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current provider configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfo"];
                };
            };
        };
    };
    get_provider_raw_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw whisper/provider config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhisperConfig"];
                };
            };
        };
    };
    set_raw_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhisperConfig"];
            };
        };
        responses: {
            /** @description The persisted provider config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhisperConfig"];
                };
            };
        };
    };
    reset_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reset provider config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhisperConfig"];
                };
            };
        };
    };
    get_provider_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"];
                };
            };
        };
    };
    run_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderTestRequest"];
            };
        };
        responses: {
            /** @description Provider test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderTestResult"];
                };
            };
        };
    };
    recording_status: {
        parameters: {
            query?: {
                /** @description Set to `waybar` for Waybar-formatted response */
                style?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recording status (default JSON shape) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingStatusResponse"];
                };
            };
        };
    };
    get_system_deps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description External tool availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDeps"];
                };
            };
        };
    };
    install_ffmpeg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FFmpeg already installed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
            /** @description Install kicked off */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
            /** @description Install already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
        };
    };
    get_install_ffmpeg_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current install state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
        };
    };
    toggle_recording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Optional per-job overrides */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleRequest"];
            };
        };
        responses: {
            /** @description Toggle dispatched; reflects immediate phase */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleResponse"];
                };
            };
        };
    };
    get_auto_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether auto-update is enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoUpdateState"];
                };
            };
        };
    };
    set_auto_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoUpdateRequest"];
            };
        };
        responses: {
            /** @description Auto-update flag after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoUpdateResponse"];
                };
            };
        };
    };
    check_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current vs available version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateReport"];
                };
            };
        };
    };
    install_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInstallRequest"];
            };
        };
        responses: {
            /** @description Result of the install attempt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateReport"];
                };
            };
        };
    };
    service_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daemon name and version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
}
